### ISSUE TITLE
Hinges fixes

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#27]
Hinges appear to have been with multiple instantiation in the model both as Physical Object and Man-Made Object, but this is not needed since Man-Made Object inherits everything from Physical Object.

Also in some cases e.g.:

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Freg5500_jira659_control%2Fextant%2Fcomponent%2Fhinges

the split damage appears multiple times with different URIs, e.g. in this case:

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Fa148a45d-cf99-4e9a-8a13-246d07ae58e0
https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Fa32aea5a-d126-4674-90ba-3d550c7f8932
https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Fd288cb0f-f71d-4bc1-8490-161b680a35c8

Are these separate instances of split, or repeated because of error?

**Comment by ryunleeuu** [comment]
The multiple instantiation is fixed in the mapping, but the Condition_State issue is a bit complicated. 

The provided example (and there will be more cases like this) is a matter of both separate instances of splitting and unfortunately also not technically a separate instance. On our forms, conservators have had checkboxes for condition reporting in a consistent way throughout the years as

Hinges
___split  ___at front  ___at back

where the first check states that the condition is present in any capacity, and the next two checks state a place of damage.
So in the example instances given, all three of these boxes have been checked OR the conservator checked only the first box.

One of the issues with this that Kristen and I discussed as I was writing the XPath is the ambiguity when a conservator has only checked the "present in any capacity" box alone (as in _X_split  ___at front  ___at back). We decided to assume that if the conservator did this, then they meant in a kind of shorthand that something was split at front and back and they didn't check all three boxes because it seemed redundant, but we're not entirely certain.
<img width="825" alt="Capture" src="https://user-images.githubusercontent.com/53874455/104758472-5828dc00-5713-11eb-83e1-9796787e0a53.PNG">

**Comment by ryunleeuu** [comment]
Update: I reworked the XSLT logic to fix this as there were only 3 condition occurrences where front & back are involved as places--uploading new dataset 20210115

**Comment by natuk** [comment]
Hm, I am not sure that this is fixed. The hinges page is now empty:

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Freg5500_jira659_control%2Fextant%2Fcomponent%2Fhinges

and the split damage does not appear at all:

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Fa148a45d-cf99-4e9a-8a13-246d07ae58e0

**Comment by ryunleeuu** [comment]
I'm not sure what's happening. In the .trig version of the dataset, the specific hinges in that example appear as
![image](https://user-images.githubusercontent.com/53874455/105073889-86245e00-5a3c-11eb-94f3-c1c5c1703135.png)

and the instances of those hinges splitting (one at front and one at back) manifested as 
![image](https://user-images.githubusercontent.com/53874455/105074150-d8fe1580-5a3c-11eb-85ce-c7430bb7f0bf.png)

and

![image](https://user-images.githubusercontent.com/53874455/105074412-2bd7cd00-5a3d-11eb-8025-184e5c4f07b9.png)

and the analogous triples appear in the RDF through text search.

**Comment by natuk** [comment]
Hm, it looks like the "extant" component of the URI has been replaced by "object". This is not a problem as the dataset will work. I also see that instead of "http" you are now using "https". This may be a bit of a problem as it has bitten us in the past (in particular around vocabularies). Do you want to check that these are consistent and let me know if a new dataset is needed?

**Comment by ryunleeuu** [comment]
Sorry--This is my fault all due to my sloppiness. I forked the new transformation from something that did not have my updated URI prefixes. I'm uploading new datasets with the correct URIs ("http" instead of "https" and "extant" rather than "object")
